// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathRAG.NET.Data.Contexts;

#nullable disable

namespace PathRAG.NET.Data.Migrations
{
    [DbContext(typeof(PathRAGDbContext))]
    [Migration("20251206190826_SeedPathRAGStages")]
    partial class SeedPathRAGStages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PathRAG")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PathRAG.NET.Models.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("ChatMessages", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ChatThreads", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.ToTable("Documents", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("IndexOnPage")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.PathRAGLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompletedStages")
                        .HasColumnType("int");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("OperationType", "StartedAt");

                    b.ToTable("PathRAGLogs", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.PathRAGStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageCode")
                        .IsUnique();

                    b.ToTable("PathRAGStages", "PathRAG");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Initialize document record in database",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_CREATE",
                            StageName = "Create Document Record",
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Extract text from PDF/DOCX/TXT files",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_DECODE",
                            StageName = "Decode Content",
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Split text into token-sized chunks",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_CHUNK",
                            StageName = "Text Chunking",
                            StageOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Generate embeddings for document chunks",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_EMBED_CHUNKS",
                            StageName = "Generate Chunk Embeddings",
                            StageOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "LLM extraction of entities and relationships from chunks",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_EXTRACT_ENTITIES",
                            StageName = "Extract Entities & Relationships",
                            StageOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Merge duplicate entities with LLM",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_MERGE_ENTITIES",
                            StageName = "Merge Entities",
                            StageOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Merge duplicate relationships with LLM",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_MERGE_RELS",
                            StageName = "Merge Relationships",
                            StageOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Store entity vectors for semantic search",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_EMBED_ENTITIES",
                            StageName = "Generate Entity Embeddings",
                            StageOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Store relationship vectors for semantic search",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_EMBED_RELS",
                            StageName = "Generate Relationship Embeddings",
                            StageOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Mark document as completed",
                            IsActive = true,
                            OperationType = "DocumentUpload",
                            StageCode = "DOC_COMPLETE",
                            StageName = "Complete Processing",
                            StageOrder = 10
                        },
                        new
                        {
                            Id = 20,
                            Description = "Save user message and start processing",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_START",
                            StageName = "Initialize Message",
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 21,
                            Description = "Extract high-level and low-level keywords from query",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_KEYWORDS",
                            StageName = "Extract Keywords",
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "Generate embedding for semantic search",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_EMBED",
                            StageName = "Generate Query Embedding",
                            StageOrder = 3
                        },
                        new
                        {
                            Id = 23,
                            Description = "Vector search for relevant entities",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_SEARCH_ENTITIES",
                            StageName = "Search Entities",
                            StageOrder = 4
                        },
                        new
                        {
                            Id = 24,
                            Description = "Vector search for relevant relationships",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_SEARCH_RELS",
                            StageName = "Search Relationships",
                            StageOrder = 5
                        },
                        new
                        {
                            Id = 25,
                            Description = "Combine entities, relationships, and text units",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_BUILD_CONTEXT",
                            StageName = "Build Query Context",
                            StageOrder = 6
                        },
                        new
                        {
                            Id = 26,
                            Description = "Load previous messages from thread",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_CHAT_HISTORY",
                            StageName = "Build Chat History",
                            StageOrder = 7
                        },
                        new
                        {
                            Id = 27,
                            Description = "Generate final response with LLM",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_LLM_RESPONSE",
                            StageName = "Generate LLM Response",
                            StageOrder = 8
                        },
                        new
                        {
                            Id = 28,
                            Description = "Save assistant response and return",
                            IsActive = true,
                            OperationType = "SendMessage",
                            StageCode = "MSG_COMPLETE",
                            StageName = "Complete Message",
                            StageOrder = 9
                        },
                        new
                        {
                            Id = 30,
                            Description = "Start graph visualization query",
                            IsActive = true,
                            OperationType = "GetKnowledgeGraph",
                            StageCode = "GRAPH_START",
                            StageName = "Initialize Graph Query",
                            StageOrder = 1
                        },
                        new
                        {
                            Id = 31,
                            Description = "Fetch entities from graph database",
                            IsActive = true,
                            OperationType = "GetKnowledgeGraph",
                            StageCode = "GRAPH_LOAD_ENTITIES",
                            StageName = "Load Entities",
                            StageOrder = 2
                        },
                        new
                        {
                            Id = 32,
                            Description = "Fetch relationships from graph database",
                            IsActive = true,
                            OperationType = "GetKnowledgeGraph",
                            StageCode = "GRAPH_LOAD_RELS",
                            StageName = "Load Relationships",
                            StageOrder = 3
                        },
                        new
                        {
                            Id = 33,
                            Description = "Construct graph visualization data",
                            IsActive = true,
                            OperationType = "GetKnowledgeGraph",
                            StageCode = "GRAPH_BUILD",
                            StageName = "Build Graph Response",
                            StageOrder = 4
                        },
                        new
                        {
                            Id = 34,
                            Description = "Return graph data",
                            IsActive = true,
                            OperationType = "GetKnowledgeGraph",
                            StageCode = "GRAPH_COMPLETE",
                            StageName = "Complete Graph Query",
                            StageOrder = 5
                        });
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.PathRAGStageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemsProcessed")
                        .HasColumnType("int");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("StageId");

                    b.HasIndex("LogId", "StageId");

                    b.ToTable("PathRAGStageLogs", "PathRAG");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("PathRAG.NET.Models.Entities.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.DocumentChunk", b =>
                {
                    b.HasOne("PathRAG.NET.Models.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.PathRAGStageLog", b =>
                {
                    b.HasOne("PathRAG.NET.Models.Entities.PathRAGLog", "Log")
                        .WithMany("StageLogs")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathRAG.NET.Models.Entities.PathRAGStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.ChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("PathRAG.NET.Models.Entities.PathRAGLog", b =>
                {
                    b.Navigation("StageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
